import banach_algebras_continuous_functions_function_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace banach_algebras_continuous_functions_function_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end banach_algebras_continuous_functions_function_theorem_canonical_lane_mathlib
end HautevilleHouse
